# Generated by Django 4.1.3 on 2023-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iaga", models.CharField(blank=True, max_length=10, null=True)),
                ("glon", models.FloatField(blank=True, null=True)),
                ("glat", models.FloatField(blank=True, null=True)),
                ("sza", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
